spring.application.name=PaymentSystem

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=paymentdb
spring.data.mongodb.auto-index-creation=false
# spring.data.mongodb.uri=mongodb+srv://shantanup:QBJMjzJw17fpAm90@cluster0.q4n3pte.mongodb.net/?appName=Cluster0


server.port=8082
# Suppress CORS HandlerMappingIntrospector cache miss warning
logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=ERROR